# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title of post.', max_length=255, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 7, 51, 27, 244517))),
                ('tags', models.TextField(default='#programming', max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'default_related_name': 'posts',
            },
        ),
    ]
