export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS';
export const SET_SELECTED_SORTING = 'SET_SELECTED_SORTING';
export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE';
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const GET_FILTERS_REQUEST = 'GET_FILTERS';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILED = 'GET_FILTERS_FAILED';

export const GET_SORTINGS_REQUEST = 'GET_SORTINGS_REQUEST';
export const GET_SORTINGS_SUCCESS = 'GET_SORTINGS_SUCCESS';
export const GET_SORTINGS_FAILED = 'GET_SORTINGS_FAILED';
