export const GET_FILTERS_REQUEST = 'GET_FILTERS';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILED = 'GET_FILTERS_FAILED';

export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS';
