export const GET_SORTINGS_REQUEST = 'GET_SORTINGS_REQUEST';
export const GET_SORTINGS_SUCCESS = 'GET_SORTINGS_SUCCESS';
export const GET_SORTINGS_FAILED = 'GET_SORTINGS_FAILED';

export const SET_SELECTED_SORTING = 'SET_SELECTED_SORTING';
